### ISSUE TITLE
Does anyone know PHP?

### ISSUE THREAD

**Issue by amazinigmech2418** [apex-os/Apex-Exascale-cloud#1]
We need PHP in order to get the API connected to the server and then connect to multiple computers for the exascale system to work.

**Comment by amazinigmech2418** [comment]
Also, if we don't end up using the exascale cloud, full systems running it will crash. I did it once and my browser crashed.

**Comment by amazinigmech2418** [comment]
I'm learning PHP right now... Hope it will be able to access a database!

**Comment by redmangospros** [comment]
I know some PHP

**Comment by amazinigmech2418** [comment]
I'm using <a href="https://www.w3schools.com">w3schools</a> to learn PHP. If you don't know PHP, you could learn there. It would still be more helpful for someone who already knows it to be able to manage the API though.

**Comment by amazinigmech2418** [comment]
@redmangospros I'll have to check with @CStafford-14 to see if you can join.

**Comment by redmangospros** [comment]
Okay, I Would Love to join.

**Comment by amazinigmech2418** [comment]
Awesome! Going to his Scratch profile right now!

**Comment by redmangospros** [comment]
My acc is blocked, @bobbyguy5 Ws me from a differnt Place

**Comment by amazinigmech2418** [comment]
I just asked him if you could join!

**Comment by redmangospros** [comment]
Great!

**Comment by amazinigmech2418** [comment]
Why was your account blocked?

**Comment by redmangospros** [comment]
Long story...

**Comment by amazinigmech2418** [comment]
OK.

**Comment by redmangospros** [comment]
/../
/./ //

**Comment by redmangospros** [comment]
[myt.zip](https://github.com/apex-os/Apex-Exascale-cloud/files/1633220/myt.zip)

**Comment by amazinigmech2418** [comment]
How did you do that? You added a file to the exascale cloud!

**Comment by herronjo** [comment]
Hey, something we need to note is that my server doesn't run PHP. My server runs my webserver (https://github.com/herronjo/joshiehttp), which uses the SJS format (something I made). Think node.js. Feel free to examine the source of the server to fully understand the mechanics of that system, or I could teach. I could run Apache with PHP if we absolutely needed to, but Apache seems unstable on my server.

**Comment by amazinigmech2418** [comment]
OK! I'll look at the code. We'll also need 2-way communication between machines for the system to work.

**Comment by herronjo** [comment]
Lucky us, GET and POST are supported in SJS, making for easy APIs.

**Comment by CStafford-14** [comment]
Looks like you're on task! I don't know much PHP, and I was intending to work solely on Prime for now.

**Comment by redmangospros** [comment]
G

**Comment by amazinigmech2418** [comment]
Whatever we're using for the server interactions is ready for use! Who should add it? I think node would be better since it's already a js file... We could also use AJAX to communicate with PHP or ASP.

**Comment by CStafford-14** [comment]
Great! I’m not into JS yet, so I’d say you make the decision. If @herronjo is available for it, we can use his server.

**Comment by amazinigmech2418** [comment]
@herronjo Does your server have the ASP.NET framework? That's needed for an ASP connection which would be more convenient since I already know it.

**Comment by amazinigmech2418** [comment]
@CStafford-14 @herronjo Which would be best? Node.js, PHP, or ASP.NET?

**Comment by CStafford-14** [comment]
I'm pretty sure @herronjo said PHP isn't supported, and we should use JS.

Message from the team:

> Hello, @AmazingMech2418. Azetrico has decided that if you can't get fully connected to the team as required, you are to be let go from the team. This is your final warning. You have 24 hours to reply to this message or sign up for the accounts.. - Azetrico Technologies Inc. - Sent via @CStafford-14

**Comment by herronjo** [comment]
Oh. Well, node.js is best for me, but it all depends on you. The server does not have ASP.NET

**Comment by redmangospros** [comment]
I know some PHP

**Comment by CStafford-14** [comment]
I don't know if @herronjo's server support PHP. Besides, we don't need to use PHP in what we're working on now. We're working on Apex Prime, the real OS.

**Comment by redmangospros** [comment]
Can I Help this?

**Comment by CStafford-14** [comment]
You need to apply on our website. https://cstaffordservices.wixsite.com/apex/apply-for-the-team

**Comment by amazinigmech2418** [comment]
@redmangospros I would suggest not joining. You'll get kicked just for not getting accounts you're not allowed to get. If you end up getting accepted, I suggest leaving immediately.

**Comment by redmangospros** [comment]
Delate your comment
