### ISSUE TITLE
This repo will need to be shut down. You no longer have permission to use any of my code.

### ISSUE THREAD

**Issue by amazinigmech2418** [apex-os/Apex-Exascale-cloud#2]

**Comment by amazinigmech2418** [comment]
@CStafford-14 Hope you like removing me... You no longer have Exascale cloud, normal cloud, welcome page, or Aurora since you removed me.

**Comment by APEXCCPlymJoe** [comment]
@amazinigmech2418 We can simply roll back...

**Comment by amazinigmech2418** [comment]
Please delete this repo though since you can't use it anymore.

**Comment by APEXCCPlymJoe** [comment]
@amazinigmech2418 No one outside of the Azetrico team can delete repositories unless it violates their privacy.

**Comment by amazinigmech2418** [comment]
You're practically stealing my code!

**Comment by APEXCCPlymJoe** [comment]
Not really

**Comment by amazinigmech2418** [comment]
Yes actually. I made this code and you're using it! I even added the MIT license. Look at the commits!

**Comment by APEXCCPlymJoe** [comment]
Deleting them now
